language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - rustup component add clippy-preview || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
script:
  - cargo clippy --all-targets
  - cargo test
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
