language: rust
services: docker
sudo: required
env:
  global:
    - CRATE_NAME=katwebx
matrix:
  include:
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    # Ring dependency does not support MIPS: https://github.com/briansmith/ring/issues/562
    #- env: TARGET=mips-unknown-linux-gnu
    #- env: TARGET=mips64-unknown-linux-gnuabi64
    #- env: TARGET=mips64el-unknown-linux-gnuabi64
    #- env: TARGET=mipsel-unknown-linux-gnu
    # Ring dependency does not support PowerPC: https://github.com/briansmith/ring/issues/389
    #- env: TARGET=powerpc-unknown-linux-gnu
    #- env: TARGET=powerpc64-unknown-linux-gnu
    #- env: TARGET=powerpc64le-unknown-linux-gnu
    # Ring dependency does not support s390x, and will likely not add support in the future.
    # - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    # TODO: Figure out why ring fails to build for these targets.
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1
    - env: TARGET=x86_64-pc-windows-gnu
before_install:
  - set -e
  - rustup self update
install:
  - sh ci/install.sh
  - source ~/.cargo/env || true
script:
  - bash ci/script.sh
after_script: set +e
before_deploy:
  - sh ci/before_deploy.sh
deploy:
  api_key:
    secure: g9VaVEhvYPFdSBuDUgqqXVjoPgQ+9Xke0wBVkUxX2h8AsN/DwCChiA0IdwJ+bTLNWrbcyikTOKIUiTk3bHxWJf1Zg1R7tTvS57NWowqnKW++u9xxOHL65TbYOUCIlshdf5E1jFkDPr39bL8Dn+PbCAlRdjAPGoWPvAhTnDdd75PD5z3Pk2NBLArRLVMZQVHRBGPArK1/czoNGEJBZs9FpSmBtRGwChiw2d8ZaqINdu+iJLV1kMA8vAfzO7qoB9ZEg3OHjtMVlteRPLuHok2+yFSgDCHG6nZBqLbmdmDfUpnq78Af5Vn5swyH52BaZ0I2jkgogGZXrDEj6bHTlApYIIYll3BkX3vgEUeICKechVBNwX2y5J4jUqc0a55jaKB+vHy+teobNZw0evfWBhGqjRvKVsKMlx/eh87VO/IuSKR1AJDxISWzD+ITkqiHpxYJtS7bkC1+3LGsFY/6thjosoYJX/ICcnlAp+0EnZQ48DVN3SdcdaVjCzw/mdMTFxrxwVWxQE9H+iwc1ggX/C3IsV/UI0sJzBjkghBfEtK1qPBS9B4GZmIUoT1f6sVwKrba0cK05FHFLbzSftGDwJT6vmgfRdSbKsUFfOey8yszYQG3zy/uIGmt7fjmz8gJdd9JyQzGcr1pF4gFUiS7n0VO2Mx+d4mcmm7EV8xRB4eS+VU=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true
cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo
branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master
notifications:
  email:
    on_success: never
