language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - rustup component add clippy-preview
script:
  - cargo clippy --all-targets
  - cargo test
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
